### PR TITLE
support translations for zh doc

### PR DESCRIPTION
**Pull request by awxiaoxian2020**

### CODE REVIEW

**Comment by awxiaoxian2020** [comment]
@jeffgbutler Could you please help me add some css styles? :)

**Comment by jeffgbutler** [comment]
@awxiaoxian2020 I think the basic infrastructure is now setup correctly. Do you plan to make additional commits to this PR as you translate the pages, or will you make additional PRs as you make progress?

**Comment by awxiaoxian2020** [comment]
@jeffgbutler I think I will start the next section in the future in another PR, you can merge it now :)

**Comment by jeffgbutler** [comment]
No activity on this PR for quite some time. Translation of the docs is a huge task. Feel free to reopen if you want to get back to it.

**Pull request closed without merging**
