### PR TITLE
Feature/add table subattribute_requiredcolumn

### PR DESCRIPTION
**Pull request by candyleer**
add requiredColumn attribute in table node,
this will be used to generate columns which  partial columns are used.
especially in huge table ie greater than 100 columns and change frequently but i only need less than 5 columns in this table ,thus i will config ignoreColumn attibutes more than 95 columns ,oh my god ,that seems to be a nightmare.
so this feature just  to make this easy.

`<table tableName="brands" domainObjectName="Brand" alias="b">
            <requiredColumn column="title"/>
            <requiredColumn column="hot"/>
</table>`

### CODE REVIEW

**Comment by jeffgbutler** [comment]
I understand what you're trying to accomplish with this PR and I think it is a good idea.  There are some problems with this PR - it has conflicts, and it changes the version which isn't correct.

Also, I would like to solve this in a different way.  What do you think about doing something like this:

```xml
<ignoreColumnPattern pattern="*" except="col1, col2, col3"/>
```

I think doing it this way would be a little easier to understand.

**Comment by jeffgbutler** [comment]
Or maybe this is better...

```xml
<ignoreColumnPattern pattern="*">
  <except columnName="col1"/>
  <except columnName="col2"/>
  <except columnName="col3"/>
</ignoreColumnPattern>
```

**Comment by jeffgbutler** [comment]
I'm going to close this PR but feel free to add comments to #118.  Thanks for the good idea.

**Comment by candyleer** [comment]
thanks for you reply and hope this feature will come soon.

**Pull request closed without merging**
