### PR TITLE
Calls to super methods for toString and equalsHashCode plugins

### PR DESCRIPTION
**Pull request by a-n-ermakov**
ToString and EqualsHashCode plugins now have properties for super method call for toString(), equals(Object obj) and hashCode(). Available only for classes with 'rootClass' property setted up, switched off by default.
It can be useful for tables, linked with inherited relation (i.e. Person -> Employee).

### CODE REVIEW

**Comment by hazendaz** [comment]
@a-n-ermakov Can you rebase this PR?  It otherwise looks good.  Thanks.

**Comment by a-n-ermakov** [comment]
Tests on travis failed with message:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project mybatis-generator-systests-mybatis3: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> 
> [ERROR] Command was /bin/sh -c cd /home/travis/build/mybatis/generator/core/mybatis-generator-systests-mybatis3 && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/travis/build/mybatis/generator/core/mybatis-generator-systests-mybatis3/target/jacoco.exec -jar /home/travis/build/mybatis/generator/core/mybatis-generator-systests-mybatis3/target/surefire/surefirebooter1870657246988640962.jar /home/travis/build/mybatis/generator/core/mybatis-generator-systests-mybatis3/target/surefire/surefire112035366387195700tmp /home/travis/build/mybatis/generator/core/mybatis-generator-systests-mybatis3/target/surefire/surefire_13430721730919975859tmp

Tests on local machine (Java7u79) are ok. Maybe there is hardware issues (free memory or free hdd space)? I can't repeat build one more time without git commit/

**Comment by hazendaz** [comment]
Thanks.  I am aware of the issue.  It sometimes works and i havent figured out the issue.  You can rerun your fork in travis by pulling up failed build and selecting to run again.  I have a bunch of queued changes to bring in that i have held off on due to this issue.  If you can see any specific issue you might be able to fix definitely open a pull request.  Any help tracking this down will be much appreciated!


I may just bring in my outstanding changes since they dont introduce the issue.  Ill get online probably in next 10 hours.  Maybe together we can get this fixed...


Sent from Outlook Mobile






On Tue, Apr 26, 2016 at 5:20 AM -0700, "a-n-ermakov" <notifications@github.com> wrote:





Tests on travis failed with message:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project mybatis-generator-systests-mybatis3: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
>
> [ERROR] Command was /bin/sh -c cd /home/travis/build/mybatis/generator/core/mybatis-generator-systests-mybatis3 && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/travis/build/mybatis/generator/core/mybatis-generator-systests-mybatis3/target/jacoco.exec -jar /home/travis/build/mybatis/generator/core/mybatis-generator-systests-mybatis3/target/surefire/surefirebooter1870657246988640962.jar /home/travis/build/mybatis/generator/core/mybatis-generator-systests-mybatis3/target/surefire/surefire112035366387195700tmp /home/travis/build/mybatis/generator/core/mybatis-generator-systests-mybatis3/target/surefire/surefire_13430721730919975859tmp

Tests on local machine (Java7u79) are ok. Maybe there is hardware issues (free memory or free hdd space)? I can't repeat build one more time without git commit/

---

**Comment by jeffgbutler** [comment]
Thanks for this - sorry for the delays.

**Pull request merged**
