### PR TITLE
<#205> Bug Fix

### PR DESCRIPTION
**Pull request by TroyTae**
constructorBased & JavaModelwithBlobs issue

### CODE REVIEW

**Comment by TroyTae** [comment]
@jeffgbutler 
I fixed the bug and generated files...
"All checks have failed" <- What is this?
I need to add some test code??

**Comment by jeffgbutler** [comment]
Your fix breaks some of the existing unit tests.  You can see the build log by checking the "Details" link.  You can see the errors locally also by running "mvn clean install" from the ../generator/core directory.

If you want, you could fork my branch that already has failing tests for this issue, and work on your fix there.  https://github.com/jeffgbutler/generator/tree/issue-205

If you want to do that, then close this PR, fork my branch, make your fix, send the PR to me, then I'll merge it into the main tree once the tests all pass.

**Comment by TroyTae** [comment]
@jeffgbutler 
I'm sorry I didn't read CONTRIBUTING.md.
So I tested in my DB Server;;
I will send pull request again after pass the test units in the directory(generator/core/mybatis-generator-systests-mybatis3/src/test/java/mbg/test/mb3).

**Comment by jeffgbutler** [comment]
@TroyTae  No problem.  I do strongly recommend that you fork my branch and work from there as all the testing code is already complete.  You would just need to make the fix.  I will also take a look doing a fix in the next day or two.

**Comment by TroyTae** [comment]
@jeffgbutler 
Thank you for your kindness!
Have a good weekend~

**Pull request closed without merging**
