### PR TITLE
Comment generator for model columns javadoc from db remarks

### PR DESCRIPTION
**Pull request by a-n-ermakov**
RemarksCommentGenerator based on DefaultCommentGenerator released.

For model fields, this generator adds javadoc lines, based on db remarks from introcpector.

It may be useful for model documenting. 

Usage in mybatis generator config:

        <commentGenerator type="org.mybatis.generator.internal.RemarksCommentGenerator" />

### CODE REVIEW

**Comment by a-n-ermakov** [comment]
Build success!

**Comment by jeffgbutler** [comment]
I like this idea, but maybe rework it so that it is function in the default comment generator controlled by a property?  WDYT?

Also - we really expect documentation updates when new features are added!

**Comment by a-n-ermakov** [comment]
Ok, i think this is better then the different generator. I'll rework it in this PR.

Documentation is strongly necessary, in what look or format i can implement it?

**Comment by a-n-ermakov** [comment]
Done + docs in site

**Comment by jeffgbutler** [comment]
This is really a great patch - thanks for being so thorough and doing documentation!  I might tweak it just a bit, but very well done.

**Comment by a-n-ermakov** [comment]
I was glad to help!

**Comment by a-n-ermakov** [comment]
jeffgbutler,

what about release 1.3.3? Can i expect this PR in foreseeable future? It seems that many changes took place (and a lot of time passed) from the last release 1.3.2

**Pull request merged**
