### PR TITLE
Hi, this maybe a bug and I fixed

### PR DESCRIPTION
**Pull request by zzqangel**
When I used this tool to generate code, I found that I haven't got some mapper methods.Such as 'updateByPrimaryKey' . I read the tool code, and found this method should be created, but not worked. The reason is this method calculatePrimaryKey in DatabaseIntrospector class. When my database is mysql, this method will run a exception, because of the catalog and shema param are both null. The param FullyQualifiedTable is created in the parent method and those two are setted in construct method, such as
                    stringHasValue(tc.getCatalog()) ? atn.getCatalog() : null,
                    stringHasValue(tc.getSchema()) ? atn.getSchema() : null
when TableConfiguration has non-null value then use ActualTableName catalog and TableConfiguration value is setted by user and ActualTableName is setted by query table. I think this might be a bug. I modified it as 'stringHasValue(tc.getCatalog()) ? tc.getCatalog() : atn.getCatalog()' and then I've got the mapper method that I needed.

### CODE REVIEW

**Comment by jeffgbutler** [comment]
This is not a bug. The intent of the code is that if no catalog/schema is specified in the configuration, then we don't want to write catalog and schema into the generated code - regardless of what the DB returns for catalog/schema. With MySQL it is best not to specify catalog/schema in your configuration.

There also seems to be another change in this PR related to the comment generator. And there are merge conflicts. And the build fails.

**Comment by zzqangel** [comment]
I don't understand that if we specify catalog/schema, then we use DB return catalog/shema to query primaryKey, and we use null to query if not. That doesn't make sense. And with MySQL, I can't get the code that I need with this code logic. I also don't understand why we let the code always throw exception.

**Comment by zzqangel** [comment]
And also ,I checked the code, and I didn't find conflicts, I could build the program locally.
P.S. in pom.xml
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis-parent</artifactId>
    <version>31-SNAPSHOT</version>
Maybe version could be modified to 31 without snapshot. I can't find that version and execute mvn command. On mvnrepository site I only found version 31.


https://mvnrepository.com/artifact/org.mybatis/mybatis-parent

**Comment by jeffgbutler** [comment]
Here's the travis link to the failed build: https://travis-ci.org/mybatis/generator/builds/496302228

I suspect the problem you're seeing is related to an old issue with MySQL - MySQL is not consistent with their usage of catalog and schema. For that reason, we always suggest that you NOT specify a catalog and schema in the generator configuration as it leads to issues like this.  See this page: http://www.mybatis.org/generator/usage/mysql.html

If you follow the advice on the page above and still see an issue, then please create a small test case that reproduces the problem and open a new issue on GitHub.

**Comment by zzqangel** [comment]
This is the only one table I used to generate. And I didn't specify neither catalog nor schema.

**Comment by zzqangel** [comment]
<property name="nullCatalogMeansCurrent" value="true" />
I've got this, thanks

**Pull request closed without merging**
