### PR TITLE
added ability to override trimStrings prop at the table and column level

### PR DESCRIPTION
**Pull request by mscalora**
need to override trimStrings for some tables and columns, low impact, no DTD change needed

### CODE REVIEW

**Comment by jeffgbutler** [comment]
I like this idea.  Please add documentation updates.

**Comment by mscalora** [comment]
It took me a while but I have now updated the docs.

**Comment by hazendaz** [comment]
@mscalora Can you rebase this?

**Comment by jeffgbutler** [comment]
I apologize for the delay.  Thanks for the contribution!

**Pull request merged**
