### PR TITLE
support Java source file merging

### PR DESCRIPTION
**Pull request by WongJiYong**
#595 java file merge
support Java source file merging
use https://javaparser.org/. so the maven scope from test to compile.
java source files include client,model and example.
1.Delete automatically generated code in existing files.
2.Add newly generated code to existing files.
3.And Sort by Field,Constructor,Method,InnerClass...

**i fix a bug that forget to deal with the auto generate constructor code, and create pull request again.**

Waitting for you create a subproject for this. Thank you for your work.

### CODE REVIEW

**Comment by jeffgbutler** [comment]
@WongJiYong 

The new sub-project is ready now. There is a new branch in this repo called "java-merger". Update your fork, then make a new pull request adding code to the new sub-project. You can add your code starting with this class: https://github.com/mybatis/generator/blob/java-merger/core/mybatis-generator-java-merger/src/main/java/org/mybatis/generator/javamerger/JavaParserJavaFileMerger.java

Once we get your code added and the basic tests run, then we'll work on doing some better end-to-end testing.

Let me know if you have any questions!

**Comment by WongJiYong** [comment]
i have some trouble.
1. in javaparse jar. i can pretty print like this.
``` java
public String prettyPrint(com.github.javaparser.ast.CompilationUnit unit) {
    PrettyPrinterConfiguration conf = new PrettyPrinterConfiguration();
    PrettyPrinter prettyPrinter = new PrettyPrinter(conf);
    return prettyPrinter.print(unit);
}
```
in mybatis/generator
``` java
public String prettyPrinter(org.mybatis.generator.api.dom.java.CompilationUnit  unit) {
    DefaultJavaFormatter formatter = new DefaultJavaFormatter();
    return formatter.getFormattedContent(unit);
}
```
but if the automatically generated java file has not changed. There will be a little difference in using javaparse to format and print after the merge,This is what we don't want to see,and is not friendly to version control.
so i need time to convert `com.github.javaparser.ast.CompilationUnit` to `org.mybatis.generator.api.dom.java.CompilationUnit` then pretty print it.
Or you give other suggestions?

**Comment by jeffgbutler** [comment]
I don't think it makes sense to try ant convert from one DOM to another - that would be a very difficult task. But I think you can configure the PrettyPrinter in JavaParser so that it will closely match the code that comes out of the generator normally.

**Comment by jeffgbutler** [comment]
Here are some settings to start with:

```java
PrettyPrinterConfiguration conf = new PrettyPrinterConfiguration();
conf.setIndentSize(4);
conf.setIndentType(IndentType.SPACES);
conf.setIndentCaseInSwitch(false);
```
This should get you close, then you can tweak it as needed.

**Comment by WongJiYong** [comment]
Yes, this config is default.
The merged format is very close to the auto generated format.
It's just a few line breaks that are different. and the  toString statements of model class.

**Comment by jeffgbutler** [comment]
Closed in favor of #606

**Pull request closed without merging**
