### PR TITLE
Fix travis builds

### LINKED ISSUE #77: Travis builds fail
Travis builds have been failing for at least 5 months.  I went back to prior successful builds and those fail too.  It's not failing locally so it would seem it's possible something changed on travis that is causing this.  

Failures fail in different spots but always close to same are in build on the mybatis3 test module.

The errors all end like this.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project mybatis-generator-systests-mybatis3: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

### PR DESCRIPTION
**Pull request by hazendaz**
Fixes #77

### CODE REVIEW

**Comment by jeffgbutler** [comment]
Hey Jeremy - I just fixed this in my fork by giving surefire some additional memory per this post:

http://stackoverflow.com/questions/23260057/the-forked-vm-terminated-without-saying-properly-goodbye-vm-crash-or-system-exi/33757854#33757854

**Comment by hazendaz** [comment]
@jeffgbutler I had tried more memory but didn't seem to work.  A lot of other people started experiencing issues back around February which was right on the timeline when this stopped working.  Turning on sudo did fix it for jdk 8 and 7 from oracle.  The open jdk continued to fail until I added the short name.  Then it all worked.  Since I didn't see it state any issues with memory during build and final build memory (although questionable) was very low, do you think this truely is just memory?

**Comment by hazendaz** [comment]
And of course as I post, openjdk7 just failed again :(.  If your fix works, lets go with that.

**Comment by jeffgbutler** [comment]
I believe it is memory.  There are hundreds of tests so I wouldn't be surprised if that was it.  I'll merge mine in and we'll see - but it works in my fork.

**Comment by hazendaz** [comment]
Memory was it!  I had only half that set when I tried.  I'm closing my PR in favor of yours :)

**Comment by jeffgbutler** [comment]
Yay!

**Pull request closed without merging**
