### PR TITLE
Support for DM database.

### PR DESCRIPTION
**Pull request by Joy1024**
Support for DM database.

### CODE REVIEW

**Comment by jeffgbutler** [comment]
What is DM database?

**Comment by Joy1024** [comment]
A Chinese popular database,  hope can sync to main branch.

在 2022/6/5 19:50, Jeff Butler 写道:

**Comment by jeffgbutler** [comment]
This PR includes several unnecessary changes that are not related to the basic request (pom changes, debug logging stuff, etc.). We would also want some documentation about DM.

I would also say that this change isn't really needed for a couple of reasons:

1. You should be using the JDBC native support for identity columns rather than this old style that causes a subsequent query
2. If you must use the old style for some reason, you can just use the DM specific phrase rather than this shortcut

**Comment by Joy1024** [comment]
This is DM(DaMeng) database official  website: https://www.dameng.com

 1. Is a MySQL compatible database.
 2. It needs only a some change（acquire primary key after insert） .

在 2022/6/5 20:08, Jeff Butler 写道:

**Comment by jeffgbutler** [comment]
If it is MySQL compatible, it would be better to use `<generatedKey sqlStatement="JDBC"/>`. This is the recommended way to retrieve identity column values since JDBC 3.0.

**Comment by Joy1024** [comment]
Ok, Thank you. I will try it using the method. 





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mybatis/generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月5日(星期天) 晚上9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mybatis/generator] Support for DM database. (PR #847)





 
If it is MySQL compatible, it would be better to use <generatedKey sqlStatement="JDBC"/&gt;. This is the recommended way to retrieve identity column values since JDBC 3.0.

**Pull request closed without merging**
