### PR TITLE
Support travis builds for jdk 15/16

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
@jeffgbutler Timestamps are slightly longer on jdk 15/16.   Now sure when that changed but set the 3 tests in question to just run for jdk 8 through 11 for now.

**Comment by jeffgbutler** [comment]
@hazendaz I'm not seeing any issues with Adopt Open JDK 15 on my local builds. What did you see?

**Comment by jeffgbutler** [comment]
@hazendaz Never mind - I see it now. Doesn't happen locally, only on Travis which must be some kind of localization thing. I'll fix the tests to use "close to" rather than exact asserts.

**Comment by hazendaz** [comment]
@jeffgbutler For reference, I had only saw it on travis.  I was being lazy and only using jdk 8 locally :)

**Pull request merged**
