### PR TITLE
Missing imported types if it has type parameters

### PR DESCRIPTION
**Pull request by iameinstein**
Fix the issue that have both imported type and full type name in the same time

### CODE REVIEW

**Comment by jeffgbutler** [comment]
I don't know what problem this is solving. Can you add a test that shows the issue?

**Comment by iameinstein** [comment]
If the existing imported type has type parameter for example " java.util.List<java.math.BigDecimal>" then the generated class will contain import types "import java.math.BigDecimal;", "import java.util.List;" and full type name property "private java.util.List<java.math.BigDecimal> listVal;"

**Comment by jeffgbutler** [comment]
I wrote a test to try and duplicate the problem you are reporting, but I can't duplicate it. There have been a lot of changes in Java rendering since the last release, so maybe this has already been resolved?

I'm writing rendering tests in Kotlin now and I've copied the test I wrote below. Please take a look at it. If you think there is still an issue, then please add a test like this into your PR that demonstrates the problem. These tests are in `src/test/kotlin`.
 

```kotlin
package org.mybatis.generator.api.dom.java.render

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.mybatis.generator.api.dom.java.Field
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType
import org.mybatis.generator.api.dom.java.JavaVisibility
import org.mybatis.generator.api.dom.java.TopLevelClass

class TopLevelClassRendererTest {

    @Test
    fun testGH467() {
        val topLevelClass = TopLevelClass("com.test.GH467")
        topLevelClass.setVisibility(JavaVisibility.PUBLIC)
        topLevelClass.addImportedType(FullyQualifiedJavaType("java.util.List"))
        topLevelClass.addImportedType(FullyQualifiedJavaType("java.math.BigDecimal"))

        val field = Field("listVal", FullyQualifiedJavaType("java.util.List<java.math.BigDecimal>"))
        field.setVisibility(JavaVisibility.PRIVATE)
        topLevelClass.addField(field)

        val renderedTlc = TopLevelClassRenderer().render(topLevelClass)
        assertThat(renderedTlc).isEqualToNormalizingNewlines("""
                |package com.test;
                |
                |import java.math.BigDecimal;
                |import java.util.List;
                |
                |public class GH467 {
                |    private List<BigDecimal> listVal;
                |}
                """.trimMargin())
    }
}
```

**Comment by iameinstein** [comment]
Base on the code at `/org/mybatis/generator/codegen/mybatis3/model/BaseRecordGenerator.java:99` the testing code should be changed like this:

`package org.mybatis.generator.api.dom.java.render

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.mybatis.generator.api.dom.java.Field
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType
import org.mybatis.generator.api.dom.java.JavaVisibility
import org.mybatis.generator.api.dom.java.TopLevelClass

class TopLevelClassRendererTest {

    @Test
    fun testGH467() {
        val topLevelClass = TopLevelClass("com.test.GH467")
        topLevelClass.setVisibility(JavaVisibility.PUBLIC)

        val type = FullyQualifiedJavaType("java.util.List<java.math.BigDecimal>")
        topLevelClass.addImportedType(type)

        val field = Field("listVal", type)
        field.setVisibility(JavaVisibility.PRIVATE)
        topLevelClass.addField(field)

        val renderedTlc = TopLevelClassRenderer().render(topLevelClass)
        assertThat(renderedTlc).isEqualToNormalizingNewlines("""
                |package com.test;
                |
                |import java.math.BigDecimal;
                |import java.util.List;
                |
                |public class GH467 {
                |    private List<BigDecimal> listVal;
                |}
                """.trimMargin())
    }
}`

**Comment by jeffgbutler** [comment]
Got it - thanks for the fix!

**Pull request merged**
