### PR TITLE
in oracle,   when data type is nvarchar2, match it to nvarchar  , whe…

### PR DESCRIPTION
**Pull request by benjaminliu**
…n data type is varchar2, match it to varchar, which finally match to String, instead of object.

when forceBigDecimals == false, if length > 18 or getScale() > 0 , use double instead of BigDecimal.

### CODE REVIEW

**Comment by benjaminliu** [comment]
import mission package

**Comment by benjaminliu** [comment]
reopen

**Comment by jeffgbutler** [comment]
Lots of problems with this:

1. This change breaks the build
2. I don't think the VARCHAR2 part of this is valid.  Oracle's JDBC driver already maps VARCHAR2 columns to JDBC Type VARCHAR.  So that part of this PR isn't needed.
3. I don't agree with the change to handling BigDecimal fields.  I do agree that very small BigDecimals (length 2 or less) could be mapped to a Byte, but the other changes aren't correct.  If the scale is > 0 then we need to use a BigDecimal because BigDecimal is exact and Double is not.

**Comment by benjaminliu** [comment]
i don't know why, but my table with nvarchar2 generate  object filed, and i got a lot of BigDecimal,  maybe i should use  custom type handler instead

**Comment by benjaminliu** [comment]
close it

**Pull request closed without merging**
