### PR TITLE
Add DomainObjectRenamingRule to rename the domain object name.

### PR DESCRIPTION
**Pull request by abel533**
`DomainObjectRenamingRule` class  is used to specify a renaming rule for table's domain object name. If `domainObjectName` is not configured, we'll build the domain object named based on the `tableName` or `runtimeTableName`. And then we use the domain object renameing rule to generate the final domain object name. 

For example, if some tables are named:
- SYS_USER
- SYS_ROLE
- SYS_FUNCTIONS

Sometimes, it might be annoying to have the generated domain name all containing the `SYS` prefix. This class can be used to remove the prefix by specifying

```
searchString = "^SYS"
replaceString=""
```

Note that internally, the generator uses the `java.util.regex.Matcher.replaceAll` method for this function. See the documentation of that method for example of the regular expression language used in Java.

In generatreConfig.xml, use like this:

``` xml
<table tableName="sys%">
    <generatedKey column="id" sqlStatement="Mysql"/>
    <domainObjectRenamingRule searchString="^Sys"/>
</table>
```

`SYS_USER` corresponding to the names of all the following:
- `User`
- `UserExample`
- `UserMapper`
- `UserMapper.xml`

### CODE REVIEW

**Comment by abel533** [comment]
@jeffgbutler

**Comment by abel533** [comment]
@jeffgbutler

**Comment by jeffgbutler** [comment]
This seems like a good idea.  I have a couple of comments:

1. Please remove the change to ibator-config_1_0.dtd.  We won't change that file at Apache, so it is kind of misleading to change it here.
2. Can you add some tests?
3. Do you want to try to write the documentation for this?

**Comment by abel533** [comment]
@jeffgbutler I have  remove the change to ibator-config_1_0.dtd. and I add a simple document.

**Comment by abel533** [comment]
@jeffgbutler then sencond commit Support table attribute mapperName use like "{0}Dao"

config table as following:
```xml
<table tableName="sys%" mapperName="{0}Dao"/>
```
then all tables mapper name will be SysUserDao,SysRoleDao...

**Comment by jeffgbutler** [comment]
@abel533 Your new commit ({0}Dao) is really a new feature and it has no tests or documentation.  Please remove it as this is something that could easily be done in a plugin.

I'll accept the other part of this PR once I have time to write some tests for it.

**Comment by abel533** [comment]
@jeffgbutler I have remove the second commit.

**Comment by jeffgbutler** [comment]
I'm not going to have time to write the tests for this, so I'm going to close it.  And the second commit that I asked you to remove is back.

I think you can probably accomplish what you want to do with a plugin.

I'm open to the idea of this as I've said, but I don't have time to do it myself and I won't accept this PR without test coverage.  If you find time to write tests, then you could submit a new PR including your first commit and some test code and I will review it.

**Pull request closed without merging**
